-- BTIS v1.0 — Bridgeport Traffic Intelligence System
-- Run in Supabase SQL Editor as project owner.

create extension if not exists pgcrypto;

create type public.app_role as enum ('admin','transportation','school','executive');
create type public.bus_status as enum ('active','maintenance','inactive');
create type public.route_period as enum ('AM','PM','MIDDAY');
create type public.incident_severity as enum ('low','medium','high','critical');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  role public.app_role not null default 'school',
  school_id bigint,
  created_at timestamptz not null default now()
);

create table public.schools (
  id bigint generated by default as identity primary key,
  school_name text not null unique,
  school_code text unique,
  address text,
  latitude double precision not null,
  longitude double precision not null,
  start_time time,
  dismissal_time time,
  student_count integer not null default 0 check (student_count >= 0),
  bus_count integer not null default 0 check (bus_count >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id)
);

alter table public.profiles
  add constraint profiles_school_id_fkey foreign key (school_id)
  references public.schools(id) on delete set null;

create table public.buses (
  id bigint generated by default as identity primary key,
  bus_number text not null unique,
  driver_name text,
  vendor text,
  capacity integer check (capacity is null or capacity > 0),
  status public.bus_status not null default 'active',
  current_latitude double precision,
  current_longitude double precision,
  current_speed numeric(6,2),
  delay_minutes integer not null default 0,
  last_gps_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id)
);

create table public.routes (
  id bigint generated by default as identity primary key,
  route_number text not null unique,
  school_id bigint not null references public.schools(id) on delete cascade,
  bus_id bigint references public.buses(id) on delete set null,
  period public.route_period not null default 'AM',
  scheduled_start time,
  scheduled_end time,
  estimated_minutes integer check (estimated_minutes is null or estimated_minutes >= 0),
  distance_miles numeric(8,2) check (distance_miles is null or distance_miles >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id)
);

create table public.route_stops (
  id bigint generated by default as identity primary key,
  route_id bigint not null references public.routes(id) on delete cascade,
  stop_order integer not null check (stop_order > 0),
  stop_name text,
  address text,
  latitude double precision not null,
  longitude double precision not null,
  scheduled_time time,
  unique(route_id, stop_order)
);

create table public.traffic_incidents (
  id bigint generated by default as identity primary key,
  incident_type text not null,
  severity public.incident_severity not null default 'medium',
  road text,
  latitude double precision not null,
  longitude double precision not null,
  start_time timestamptz not null default now(),
  end_time timestamptz,
  description text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id)
);

create table public.gps_positions (
  id bigint generated by default as identity primary key,
  bus_id bigint not null references public.buses(id) on delete cascade,
  latitude double precision not null,
  longitude double precision not null,
  speed numeric(6,2),
  heading numeric(6,2),
  recorded_at timestamptz not null default now()
);

create index gps_positions_bus_time_idx on public.gps_positions(bus_id, recorded_at desc);
create index incidents_active_idx on public.traffic_incidents(active, start_time desc);
create index routes_school_idx on public.routes(school_id);

create or replace function public.current_role()
returns public.app_role
language sql stable security definer set search_path = public
as $$ select role from public.profiles where id = auth.uid() $$;

create or replace function public.is_admin_or_transportation()
returns boolean
language sql stable security definer set search_path = public
as $$ select coalesce(public.current_role() in ('admin','transportation'), false) $$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles(id,email,full_name,role)
  values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name',split_part(new.email,'@',1)),'school')
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.schools enable row level security;
alter table public.buses enable row level security;
alter table public.routes enable row level security;
alter table public.route_stops enable row level security;
alter table public.traffic_incidents enable row level security;
alter table public.gps_positions enable row level security;

create policy "profiles read own or admin" on public.profiles for select
using (id = auth.uid() or public.current_role() = 'admin');
create policy "profiles admin update" on public.profiles for update
using (public.current_role() = 'admin') with check (public.current_role() = 'admin');

create policy "authenticated read schools" on public.schools for select to authenticated using (true);
create policy "ops manage schools" on public.schools for all to authenticated
using (public.is_admin_or_transportation()) with check (public.is_admin_or_transportation());

create policy "authenticated read buses" on public.buses for select to authenticated using (true);
create policy "ops manage buses" on public.buses for all to authenticated
using (public.is_admin_or_transportation()) with check (public.is_admin_or_transportation());

create policy "authenticated read routes" on public.routes for select to authenticated using (true);
create policy "ops manage routes" on public.routes for all to authenticated
using (public.is_admin_or_transportation()) with check (public.is_admin_or_transportation());

create policy "authenticated read stops" on public.route_stops for select to authenticated using (true);
create policy "ops manage stops" on public.route_stops for all to authenticated
using (public.is_admin_or_transportation()) with check (public.is_admin_or_transportation());

create policy "authenticated read incidents" on public.traffic_incidents for select to authenticated using (true);
create policy "ops manage incidents" on public.traffic_incidents for all to authenticated
using (public.is_admin_or_transportation()) with check (public.is_admin_or_transportation());

create policy "authenticated read gps" on public.gps_positions for select to authenticated using (true);
create policy "ops manage gps" on public.gps_positions for all to authenticated
using (public.is_admin_or_transportation()) with check (public.is_admin_or_transportation());

-- Realtime tables
alter publication supabase_realtime add table public.buses;
alter publication supabase_realtime add table public.traffic_incidents;
alter publication supabase_realtime add table public.gps_positions;

-- Starter Bridgeport demonstration data (replace/expand with district-authoritative data)
insert into public.schools (school_name, school_code, address, latitude, longitude, start_time, dismissal_time, student_count, bus_count)
values
('Bassick High School','0150115','1181 Fairfield Ave, Bridgeport, CT',41.1768,-73.2174,'07:53','14:30',1243,29),
('Central High School','0151215','1 Lincoln Blvd, Bridgeport, CT',41.2015,-73.2098,'07:53','14:30',1787,34),
('Harding High School','0151015','379 Bond St, Bridgeport, CT',41.1862,-73.1633,'07:53','14:30',1098,27),
('Cesar Batalla School','0151411','606 Howard Ave, Bridgeport, CT',41.1747,-73.2157,'08:40','15:10',950,18),
('Blackham School','0154011','425 Thorme St, Bridgeport, CT',41.2141,-73.2182,'08:40','15:10',875,16)
on conflict (school_name) do nothing;

insert into public.buses(bus_number,driver_name,vendor,capacity,status,current_latitude,current_longitude,current_speed,delay_minutes,last_gps_at)
values
('121','Demo Driver 1','District Vendor',71,'active',41.1840,-73.2050,24,0,now()),
('214','Demo Driver 2','District Vendor',71,'active',41.1940,-73.1810,18,4,now()),
('089','Demo Driver 3','District Vendor',71,'active',41.1710,-73.1910,9,13,now())
on conflict (bus_number) do nothing;

insert into public.routes(route_number,school_id,bus_id,period,scheduled_start,scheduled_end,estimated_minutes,distance_miles)
select 'BASS-PM-01',s.id,b.id,'PM','14:30','15:20',50,12.4 from public.schools s, public.buses b
where s.school_name='Bassick High School' and b.bus_number='121'
on conflict (route_number) do nothing;

insert into public.traffic_incidents(incident_type,severity,road,latitude,longitude,description,active)
values
('Construction','high','North Avenue',41.1987,-73.2010,'Lane restriction — demonstration record',true),
('Congestion','medium','Fairfield Avenue',41.1758,-73.2134,'Heavy school dismissal traffic — demonstration record',true);

-- Make your first account an administrator after creating it in Authentication:
-- update public.profiles set role='admin' where lower(email)=lower('YOUR_EMAIL@bridgeportedu.net');
